### ISSUE TITLE
Blocco dell'applicazione in caso di mancato dispositivo di cattura video

### ISSUE THREAD

**Issue by alessandrods** [TryKatChup/Poke-Pi-Dex#1]
Se non è presente alcun dispositivo di cattura video, o questo viene disconnesso, l'applicazione si blocca e non visualizza alcun messaggio di errore.

**Comment by mikyll** [comment]
Test:
- su Windows, disabilitando il dispositivo della fotocamera: ✔️ 
- su Raspberry Pi, senza picamera collegata: ✔️

**Comment by mikyll** [comment]
Test:
- su Windows, disabilitando il dispositivo della fotocamera: ✔️ 
- su Raspberry Pi, senza picamera collegata: ✔️

**Comment by mikyll** [comment]
Test:
- su Windows, con una sorgente valida: ✔️
- su Windows, con una sorgente non valida: ✔️
- su Raspberry Pi, senza picamera collegata: ✔️

<img width=400px src="https://user-images.githubusercontent.com/56556806/222853749-60176a2a-3a8d-4e3a-99c2-722892944984.png">
